export const CHANNEL_IN_APP = 'in_app';
export const SOURCE_AUTOMATIC = 'automatic';
export const SOURCE_MANUAL = 'manual';

export const AUDIENCES = [
  'all',
  'users',
  'mentors',
  'admins',
  'registered_participants',
  'approved_volunteers',
  'affected_volunteers',
  'specific_user',
  'question_author',
];

export const ENTITY_TYPES = [
  'event',
  'volunteering',
  'community_question',
  'community_reply',
  'course',
  'meditation',
  'camp',
  'support_ticket',
];

export const NOTIFICATION_TYPES = {
  EVENT_PUBLISHED: 'EVENT_PUBLISHED',
  EVENT_REGISTRATION_CONFIRMED: 'EVENT_REGISTRATION_CONFIRMED',
  EVENT_UPDATED: 'EVENT_UPDATED',
  EVENT_CANCELLED: 'EVENT_CANCELLED',
  EVENT_REMINDER: 'EVENT_REMINDER',
  EVENT_CERTIFICATE_AVAILABLE: 'EVENT_CERTIFICATE_AVAILABLE',
  VOLUNTEERING_PUBLISHED: 'VOLUNTEERING_PUBLISHED',
  VOLUNTEERING_APPLICATION_SUBMITTED: 'VOLUNTEERING_APPLICATION_SUBMITTED',
  VOLUNTEERING_APPLICATION_APPROVED: 'VOLUNTEERING_APPLICATION_APPROVED',
  VOLUNTEERING_APPLICATION_REJECTED: 'VOLUNTEERING_APPLICATION_REJECTED',
  VOLUNTEERING_UPDATED: 'VOLUNTEERING_UPDATED',
  VOLUNTEERING_CANCELLED: 'VOLUNTEERING_CANCELLED',
  VOLUNTEERING_REMINDER: 'VOLUNTEERING_REMINDER',
  VOLUNTEERING_COMPLETED: 'VOLUNTEERING_COMPLETED',
  COMMUNITY_QUESTION_ANSWERED: 'COMMUNITY_QUESTION_ANSWERED',
  COMMUNITY_COMMENT: 'COMMUNITY_COMMENT',
  COMMUNITY_MODERATION: 'COMMUNITY_MODERATION',
  NEW_COURSE: 'NEW_COURSE',
  COURSE_REMINDER: 'COURSE_REMINDER',
  NEW_CAMP: 'NEW_CAMP',
  CAMP_REMINDER: 'CAMP_REMINDER',
  CAMP_UPDATED: 'CAMP_UPDATED',
  CAMP_CANCELLED: 'CAMP_CANCELLED',
  NEW_MEDITATION: 'NEW_MEDITATION',
  ADMIN_ANNOUNCEMENT: 'ADMIN_ANNOUNCEMENT',
  SUPPORT_TICKET_CREATED: 'SUPPORT_TICKET_CREATED',
  SUPPORT_TICKET_REPLY: 'SUPPORT_TICKET_REPLY',
  SUPPORT_TICKET_STATUS_UPDATED: 'SUPPORT_TICKET_STATUS_UPDATED',
};

export const TRANSACTIONAL_TYPES = new Set([
  NOTIFICATION_TYPES.EVENT_REGISTRATION_CONFIRMED,
  NOTIFICATION_TYPES.EVENT_CANCELLED,
  NOTIFICATION_TYPES.EVENT_CERTIFICATE_AVAILABLE,
  NOTIFICATION_TYPES.VOLUNTEERING_APPLICATION_SUBMITTED,
  NOTIFICATION_TYPES.VOLUNTEERING_APPLICATION_APPROVED,
  NOTIFICATION_TYPES.VOLUNTEERING_APPLICATION_REJECTED,
  NOTIFICATION_TYPES.VOLUNTEERING_CANCELLED,
  NOTIFICATION_TYPES.VOLUNTEERING_COMPLETED,
  NOTIFICATION_TYPES.COMMUNITY_MODERATION,
  NOTIFICATION_TYPES.ADMIN_ANNOUNCEMENT,
  NOTIFICATION_TYPES.SUPPORT_TICKET_CREATED,
  NOTIFICATION_TYPES.SUPPORT_TICKET_REPLY,
  NOTIFICATION_TYPES.SUPPORT_TICKET_STATUS_UPDATED,
]);

export const REMINDER_TYPES = new Set([
  NOTIFICATION_TYPES.EVENT_REMINDER,
  NOTIFICATION_TYPES.VOLUNTEERING_REMINDER,
  NOTIFICATION_TYPES.COURSE_REMINDER,
  NOTIFICATION_TYPES.CAMP_REMINDER,
]);

export const CATEGORY_COLUMNS = {
  event: 'event_notifications',
  volunteering: 'volunteering_notifications',
  camp: 'camp_notifications',
  course: 'course_notifications',
  meditation: 'meditation_notifications',
  community_question: 'community_notifications',
  community_reply: 'community_notifications',
  community: 'community_notifications',
};

export const DEFAULT_PREFERENCES = {
  event_notifications: true,
  volunteering_notifications: true,
  camp_notifications: true,
  course_notifications: true,
  meditation_notifications: true,
  community_notifications: true,
  reminder_notifications: true,
};

export const PREFERENCE_FIELDS = Object.keys(DEFAULT_PREFERENCES);
